---
- hosts: all
  vars_files:
    - users.yml
  tasks:

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{item.username}}"
      state: "{{item.state}}"
      key: "{{ lookup('file', item.keyfile) }}"
    with_items: "{{ users }}"
      

      
